deploy_script_exporter.sh
Currently, if the GCE instance running the script_exporter gets restarted for any reason, the Docker containers are not automatically started. This PR adds the `--restart=always` flag to the `docker-run` commands so that containerd always restarts the containers.
This PR also bumps the GCE machine type for the mlab-oti project to n1-standard-8, since the other other was running out of memory and CPU.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-script-exporter/9)
=> Sets Docker containers to always restart + upgrades machine type for mlab-oti deployment

ndt_e2e.sh
Currently, Prometheus probes the script_exporter every 60 seconds. There are a lot of nodes (~400) to probe in that time. This means that `ndt_e2e.sh` gets run for all these nodes in a very short period of time, which loads the VM heavily. `ndt_e2e.sh` caches return codes for the test for 10 minutes, in the case that the test was successful. What this ultimately means is that all the cached results expire around the same time, which causes another spike in ndt_e2e test volume. This plays out as a cyclic spike and fall in resource usage every $MAX_CACHE_AGE interval.
To help avoid these huge spikes and spread out the load, this PR sets the mtime of the cache file (the first time it is created) into the past somewhere between 1s and $MAX_CACHE_AGEs. In this way, the cached results should …
=> Sets the mtime of the e2e cache file to now()-random

Dockerfile, apply_tc_rules.cron, deploy_script_exporter.sh
This PR is to resolve this issue:
https://github.com/m-lab/ops-tracker/issues/345
The script ndt_e2e.sh will refuse to run for a host (IP address) that doesn't have tc traffic filtering configured.  When sites.py gets new sites, or IPs change, the tc rules need to change. This PR sets up a daily cron job that will update the tc rules to accommodate for any changes to sites.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-script-exporter/11)
=> Sets up a daily cron job to update the tc traffic shaping rules

Dockerfile, apply_tc_rules.cron, cloud-config.yml, deploy_script_exporter.sh
@pboothe reports that in his experience running cron in a Docker container is a bad idea. Also, something is half broken about the container as it is. This removes cron and the cron job from the container in favor of having the host VM use a systemd timer to update the tc traffic shaping rules in the script_exporter container every day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-script-exporter/12)
=> Removes cron from container in favor of using a systemd timer on the host VM.

deploy_script_exporter.sh
We are currently experiencing a memory issue on the script-exporter in mlab-staging; it runs out, invoking the oom-killer, taking down the Docker containers. Until we can figure out the root cause, this PR will up the memory substantially. This can likely be undone once we figure out why memory usage is spiking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-script-exporter/16)
=> Increases the GCE machine type to n1-standard-8 for mlab-staging

ndt_e2e.sh
Currently, the test runs unencrypted on port 3001. This is fine, but is not representative of most of our traffic any longer. The bulk of our traffic is encrypted on port 3010, so one of our core availability tests should do the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/prometheus-script-exporter/17)
=> Modifies ndt_e2e.sh script to run test using encryption on port 3010.

cloud-config.yml
This service gets run daily by a systemd timer, but it was previously fairly useless because the operator repo clone was never updated, so the tc rules never changed or were updated based on changes to sites.py. This PR addresses that by making the service to a pull on the local clone of the operator repo prior to running `apply_tc_rules.sh`.
Addresses issue #20.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/21)
=> git-pulls the operator repo clone before running apply_tc_rules.sh.

Dockerfile, apply_tc_rules.sh, cloud-config.yml
The script-exporter-support script `apply-tc-rules.sh` currently has a dependency on an output format of mlabconfig.py that it no longer supports now that siteinfo is the canonical source of site information. This PR converts the apply-tc-rules.sh script to start using sites.json from the siteinfo "API" instead of mlabconfig.py. 
Also, presently the first thing apply-tc-rules.sh does is to delete all qdiscs and rules. If any of the following steps fail, then no tc rules will be set up, and if no tc rules are configured for a given IP, then ndt_e2e.sh will refuse to run and exits with an error. This can flag the entire NDT fleet as being down, causing an fleetwide outage for those clients that use mlab-ns.
This PR moves the logic of successfully fetching the NDT IP addresses before doing …
=> Migrates apply-tc-rules.sh off of sites.py and onto siteinfo sites.json

script_exporter.yml
Part of https://github.com/m-lab/ndt-server/issues/166
By default, the queueing test requests a test suite including "c2s + s2c + meta" -- but will never run them. In the new ndt-server, tests requested but never run are counted as an error.
This change modifies the requested test suite to only include the STATUS message. This way, the other tests are never attempted and never error.
Example debug output from the current and new platforms. As well, I verified ad-hoc that the web100-ndt server can return QUEUE messages when STATUS tests are requested. (ran the queuing check in background in a loop until server started to queue (mlab2.lga1t).
```
Running NDT test to wss://ndt-iupui-mlab4-lga03.measurement-lab.org:3010/ndt_protocol
OPENED CONNECTION
type = 1 (SRV_QUEUE) body = '0'
There will …
```
=> Add status-only queueing test to reduce false-error rate

ndt_e2e.sh
This change fixes a bug in ndt_e2e.sh that causes `$FIRST_RUN=false` to evaluate to true unconditionally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/28)
=> Fix evaluation bug

Dockerfile.minimal, cache_exit_code.sh
This change adds two new files to support prometheus federation deployment of the script-exporter for ndt5 e2e monitoring using access tokens.
The cache_exit_code.sh takes inspiration from `ndt_e2e.sh` but generalizes it to run any command.
The Dockerfile.minimal includes the command dependencies for the ndt5 e2e monitoring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/29)
=> Add minimal script-exporter Dockerfile

.travis.yml
This repo contains two different deployment paths now: GCE script-exporter and dockerhub build of the Dockerfile.minimal for GKE.
This PR changes the condition on production deployments to match the `production*` pattern. This preserves the current behavior for historical tag names. And, it ignores `v[0-9.]+` patterns which are recognized by dockerhub.
This change will allow deploying of each independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/30)
=> Deploy on specific tag patterns

Dockerfile.minimal
This PR updates the script-exporter container image to support running Wehe CLI tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/33)
=> Install java, clone wehe-cmdline repo

cache_exit_code.sh
Currently, if more than one script requires the `monitoring-token` command to run, then the cache directories will no longer be unique and you will have collisions, as all cache directories will be located at `/tmp/cache-monitoring-token`. This PR introduces the use of a new environment variable `EXPERIMENT` which will be used to create a unique cache directory like `/tmp/cache-${EXPERIMENT}`. The variable will be introduced into the environment directly from the script-exporter config YAML file like:
```
scripts:
- name: "rofl"
script: EXPERIMENT=rofl monitoring-token <etc>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/34)
=> Allows for unique return status caching directories

Dockerfile.minimal
We discovered that script_exporter has a problem with orphaned processes in the case where script_exporter terminates its shell while the scripts are still running. This PR adds a new tiny init ("tini") utility which can be PID 1. With this configuration, when a process gets orphaned it will be reparented to tini, which will reap it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/36)
=> Installs tini and uses it as PID 1

Dockerfile.minimal
We use the `args` key in our k8s manifest for script_exporter, which overrides anything defined in `CMD` in the Dockerfile. This PR moves the script_exporter command to ENTRYPOINT so that the k8s manifest can stay as it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/37)
=> Moves script_exporter command to ENTRYPOINT

Dockerfile.minimal
Currently, the Dockerfile points to a repo in a personal Github account. The repo was moved to more official NEU account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/38)
=> Updates Dockerfile to point to more official wehe-cmdline repo

wehe-client.sh
Today I noticed quite a lot of evicted script-exporter pods in production. Inspecting the pods they were all evicted for "DiskPressure", which means that the disk was filling up or too many inodes were being used.  Every wehe-cmdline test writes at least 2 files to disk. They are small text files, but the number of them adds up quickly in production. Eyeing it, it looks like around 5 files are written every second or so. The inode limit in the script-exporter pod is 6,258,720. It seems that under those conditions it could take around 14 days to use up every available inode, if my math is correct: 6258720 / 5 / 60 / 60 / 24
This PR modifies wehe-client.sh to remove the `test_results/` directory after every run, since we have no use for those logs, and they are likely causing problems.
--- …
=> Removes log files written by wehe-cmdline.

Dockerfile.minimal, cache_exit_code.sh
This change explicitly checks the value of `LOGX_DEBUG == true` to decide to log command output. The output log is also truncated on every invocation, rather than appended to indefinitely.
Bug found from https://github.com/m-lab/prometheus-support/pull/974 and script-exporter disk utilization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/40)
=> Explicit value check for logging

Dockerfile.minimal
This change adds the ndt7-client to the minimal script-exporter support image.
This makes it possible to have monitoring and automation targeting the autonode servers in sandbox and staging (and possibly production).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/41)
=> Add ndt7-client

Dockerfile.minimal
Running the wehe client with version 11 yielded an error that mobi/meddle/wehe/Main was compiled with a more recent version of the Java Runtime than was installed on the system. This change seems to resolve that issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/script-exporter-support/42)
=> Updates openjdk package from version 11 to 17
